//@ts-check
// Interactive glue code for ":::quiz"/":::evaluate" blocks generated by
// vite-plugin-lessons.js. Used two ways:
//   - the standalone lessons site copies this file verbatim to
//     public/lessons/_quiz.js and loads it as <script type="module">
//   - the in-app lessons panel (LessonsPanel.js) imports initQuizBlocks
//     directly and re-runs it whenever it injects new lesson HTML

/** @param {number[]} arr */
function shuffle(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** @param {HTMLElement} block */
function initMatchBlock(block) {
  const pool = block.querySelector(".quiz-match-pool");
  const explanations = JSON.parse(block.dataset.explanations || "[]");
  const indices = shuffle([...Array(explanations.length).keys()]);
  if (!pool) return;
  pool.innerHTML = "";
  for (const i of indices) {
    const chip = document.createElement("div");
    chip.className = "quiz-match-chip";
    chip.dataset.idx = String(i);
    chip.draggable = true;
    chip.textContent = explanations[i];
    pool.appendChild(chip);
  }
}

// ── Drag & drop ────────────────────────────────────────────────
/** @type {HTMLElement|null} */
let dragged = null;

// Guarded: this module is imported by SimControl.js (via LessonsPanel.js),
// which some Node-environment unit tests import purely to resolve a
// circular-import cycle, without ever touching the DOM. Registering these
// listeners must stay a no-op there instead of throwing on `document`.
if (typeof document !== "undefined") {
  document.addEventListener("dragstart", (/** @type {DragEvent} */ e) => {
    const chip = /** @type {HTMLElement|null} */ (e.target instanceof HTMLElement ? e.target.closest(".quiz-match-chip") : null);
    if (!chip) return;
    dragged = chip;
    chip.classList.add("dragging");
    if (e.dataTransfer) e.dataTransfer.effectAllowed = "move";
  });

  document.addEventListener("dragend", () => {
    if (dragged) { dragged.classList.remove("dragging"); dragged = null; }
  });

  document.addEventListener("dragover", (/** @type {DragEvent} */ e) => {
    const target = e.target instanceof HTMLElement ? e.target.closest(".quiz-match-dropzone, .quiz-match-pool") : null;
    if (target && dragged) { e.preventDefault(); target.classList.add("drag-over"); }
  });

  document.addEventListener("dragleave", (/** @type {DragEvent} */ e) => {
    const target = e.target instanceof HTMLElement ? e.target.closest(".quiz-match-dropzone, .quiz-match-pool") : null;
    if (target && !target.contains(/** @type {Node|null} */ (e.relatedTarget))) target.classList.remove("drag-over");
  });

  document.addEventListener("drop", (/** @type {DragEvent} */ e) => {
    const target = e.target instanceof HTMLElement ? e.target.closest(".quiz-match-dropzone, .quiz-match-pool") : null;
    if (!target || !dragged) return;
    e.preventDefault();
    target.classList.remove("drag-over");
    if (target.classList.contains("quiz-match-dropzone")) {
      const current = target.querySelector(".quiz-match-chip");
      if (current && dragged.parentElement) dragged.parentElement.appendChild(current);
      target.appendChild(dragged);
    } else {
      target.appendChild(dragged);
    }
  });

  // ── MC: click to select ──────────────────────────────────────
  document.addEventListener("click", (/** @type {MouseEvent} */ e) => {
    const opt = e.target instanceof HTMLElement ? e.target.closest(".quiz-option") : null;
    if (!opt) return;
    const block = opt.closest(".quiz-mc");
    if (!block || block.classList.contains("evaluated")) return;
    block.querySelectorAll(".quiz-option").forEach((o) => o.classList.remove("selected"));
    opt.classList.add("selected");
  });

  // ── Evaluate button — doubles as "try again" once evaluated ───
  document.addEventListener("click", (/** @type {MouseEvent} */ e) => {
    const btn = /** @type {HTMLButtonElement|null} */ (e.target instanceof HTMLElement ? e.target.closest(".quiz-evaluate-btn") : null);
    if (!btn) return;
    const ids = (btn.dataset.quizIds || "").split(",").filter(Boolean);
    const summary = btn.nextElementSibling;

    if (btn.dataset.mode === "retry") {
      for (const id of ids) {
        const block = /** @type {HTMLElement|null} */ (document.querySelector(`[data-quiz-id="${id}"]`));
        if (block) resetBlock(block);
      }
      if (summary) { summary.textContent = ""; summary.className = "quiz-evaluate-summary"; }
      btn.textContent = btn.dataset.originalLabel || btn.textContent;
      delete btn.dataset.mode;
      return;
    }

    let correct = 0, total = 0;
    for (const id of ids) {
      const block = /** @type {HTMLElement|null} */ (document.querySelector(`[data-quiz-id="${id}"]`));
      if (!block) continue;
      const r = evaluateBlock(block);
      correct += r.correct;
      total += r.total;
    }
    if (summary && total > 0) {
      const tpl = total === 1
        ? (document.body.dataset.quizResultOne || "{correct}/{total}")
        : (document.body.dataset.quizResultOther || "{correct}/{total}");
      summary.textContent = tpl.replace("{correct}", String(correct)).replace("{total}", String(total));
      summary.className = "quiz-evaluate-summary " + (correct === total ? "quiz-summary-ok" : "quiz-summary-err");
    }
    if (total > 0) {
      btn.dataset.originalLabel = btn.textContent || "";
      btn.textContent = document.body.dataset.quizRetry || btn.dataset.originalLabel || "";
      btn.dataset.mode = "retry";
    }
  });
}

/** Restores a block to its pre-evaluation state so the student can try again. @param {HTMLElement} block */
function resetBlock(block) {
  block.classList.remove("evaluated");
  switch (block.dataset.type) {
    case "short": {
      const input = /** @type {HTMLInputElement|null} */ (block.querySelector(".quiz-input"));
      const fb = block.querySelector(".quiz-feedback");
      if (input) { input.value = ""; input.disabled = false; input.classList.remove("quiz-correct", "quiz-incorrect"); }
      if (fb) { fb.textContent = ""; fb.className = "quiz-feedback"; }
      break;
    }
    case "mc": {
      block.querySelectorAll(".quiz-option").forEach((el) => {
        const opt = /** @type {HTMLButtonElement} */ (el);
        opt.disabled = false;
        opt.classList.remove("selected", "quiz-correct", "quiz-incorrect");
      });
      break;
    }
    case "fill": {
      block.querySelectorAll(".quiz-gap-input").forEach((el) => {
        const input = /** @type {HTMLInputElement} */ (el);
        input.value = "";
        input.disabled = false;
        input.classList.remove("quiz-correct", "quiz-incorrect");
        const fb = input.nextElementSibling;
        if (fb) { fb.textContent = ""; fb.className = "quiz-feedback"; }
      });
      break;
    }
    case "match": {
      // initMatchBlock() below creates fresh chip elements — remove the old
      // ones first (both any still in the pool and any dropped into zones),
      // or they'd linger as orphaned duplicates.
      block.querySelectorAll(".quiz-match-chip").forEach((el) => el.remove());
      block.querySelectorAll(".quiz-match-dropzone").forEach((el) => {
        el.classList.remove("quiz-correct", "quiz-incorrect", "quiz-missing");
      });
      initMatchBlock(block);
      break;
    }
  }
}

/** @param {HTMLElement} block */
function evaluateBlock(block) {
  block.classList.add("evaluated");
  switch (block.dataset.type) {
    case "short": return evalShort(block);
    case "mc":    return evalMC(block);
    case "fill":  return evalFill(block);
    case "match": return evalMatch(block);
    default:      return { correct: 0, total: 0 };
  }
}

/**
 * @param {HTMLInputElement} input
 * @param {Element|null} fb
 * @param {boolean} ok
 */
function markFeedback(input, fb, ok) {
  input.classList.toggle("quiz-correct", ok);
  input.classList.toggle("quiz-incorrect", !ok);
  input.disabled = true;
  if (fb) {
    fb.textContent = ok ? "✓" : "✗";
    fb.className = "quiz-feedback " + (ok ? "quiz-ok" : "quiz-err");
  }
}

/** @param {HTMLElement} block */
function evalShort(block) {
  const input = /** @type {HTMLInputElement} */ (block.querySelector(".quiz-input"));
  const fb = block.querySelector(".quiz-feedback");
  const answers = JSON.parse(block.dataset.answers || "[]");
  const ok = answers.includes(input.value.trim().toLowerCase());
  markFeedback(input, fb, ok);
  return { correct: ok ? 1 : 0, total: 1 };
}

/** @param {HTMLElement} block */
function evalMC(block) {
  let correct = false;
  block.querySelectorAll(".quiz-option").forEach((el) => {
    const opt = /** @type {HTMLButtonElement} */ (el);
    opt.disabled = true;
    if (opt.dataset.correct === "true") opt.classList.add("quiz-correct");
    if (opt.classList.contains("selected")) {
      correct = opt.dataset.correct === "true";
      if (!correct) opt.classList.add("quiz-incorrect");
    }
  });
  return { correct: correct ? 1 : 0, total: 1 };
}

/** @param {HTMLElement} block */
function evalFill(block) {
  let correct = 0;
  block.querySelectorAll(".quiz-gap-input").forEach((el) => {
    const input = /** @type {HTMLInputElement} */ (el);
    const answers = JSON.parse(input.dataset.answers || "[]");
    const ok = answers.includes(input.value.trim().toLowerCase());
    markFeedback(input, input.nextElementSibling, ok);
    if (ok) correct++;
  });
  const inputs = block.querySelectorAll(".quiz-gap-input");
  return { correct, total: inputs.length };
}

/** @param {HTMLElement} block */
function evalMatch(block) {
  let correct = 0;
  block.querySelectorAll(".quiz-match-chip").forEach((el) => { /** @type {HTMLElement} */ (el).draggable = false; });
  block.querySelectorAll(".quiz-match-dropzone").forEach((el) => {
    const zone = /** @type {HTMLElement} */ (el);
    const chip = /** @type {HTMLElement|null} */ (zone.querySelector(".quiz-match-chip"));
    const ok = !!chip && Number(chip.dataset.idx) === Number(zone.dataset.correctIdx);
    zone.classList.toggle("quiz-correct", ok);
    zone.classList.toggle("quiz-incorrect", !!chip && !ok);
    zone.classList.toggle("quiz-missing", !chip);
    if (ok) correct++;
  });
  return { correct, total: block.querySelectorAll(".quiz-match-dropzone").length };
}

/**
 * (Re-)initializes quiz-match blocks under `root`. Called once for the
 * whole document below; the in-app lessons panel calls it again after
 * injecting new lesson HTML, since everything else here is delegated at
 * the document level and needs no re-init.
 * @param {ParentNode} [root]
 */
export function initQuizBlocks(root = document) {
  root.querySelectorAll(".quiz-match").forEach((el) => initMatchBlock(/** @type {HTMLElement} */ (el)));
}

if (typeof document !== "undefined") initQuizBlocks();
